/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreNosRouteImport } from './routes/sobre-nos'
import { Route as ManutencaoPaleteirasHidraulicasCascavelRouteImport } from './routes/manutencao-paleteiras-hidraulicas-cascavel'
import { Route as ConsertoPaleteiraHidraulicaCascavelRouteImport } from './routes/conserto-paleteira-hidraulica-cascavel'
import { Route as IndexRouteImport } from './routes/index'

const SobreNosRoute = SobreNosRouteImport.update({
  id: '/sobre-nos',
  path: '/sobre-nos',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoPaleteirasHidraulicasCascavelRoute =
  ManutencaoPaleteirasHidraulicasCascavelRouteImport.update({
    id: '/manutencao-paleteiras-hidraulicas-cascavel',
    path: '/manutencao-paleteiras-hidraulicas-cascavel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConsertoPaleteiraHidraulicaCascavelRoute =
  ConsertoPaleteiraHidraulicaCascavelRouteImport.update({
    id: '/conserto-paleteira-hidraulica-cascavel',
    path: '/conserto-paleteira-hidraulica-cascavel',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conserto-paleteira-hidraulica-cascavel': typeof ConsertoPaleteiraHidraulicaCascavelRoute
  '/manutencao-paleteiras-hidraulicas-cascavel': typeof ManutencaoPaleteirasHidraulicasCascavelRoute
  '/sobre-nos': typeof SobreNosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conserto-paleteira-hidraulica-cascavel': typeof ConsertoPaleteiraHidraulicaCascavelRoute
  '/manutencao-paleteiras-hidraulicas-cascavel': typeof ManutencaoPaleteirasHidraulicasCascavelRoute
  '/sobre-nos': typeof SobreNosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conserto-paleteira-hidraulica-cascavel': typeof ConsertoPaleteiraHidraulicaCascavelRoute
  '/manutencao-paleteiras-hidraulicas-cascavel': typeof ManutencaoPaleteirasHidraulicasCascavelRoute
  '/sobre-nos': typeof SobreNosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conserto-paleteira-hidraulica-cascavel'
    | '/manutencao-paleteiras-hidraulicas-cascavel'
    | '/sobre-nos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conserto-paleteira-hidraulica-cascavel'
    | '/manutencao-paleteiras-hidraulicas-cascavel'
    | '/sobre-nos'
  id:
    | '__root__'
    | '/'
    | '/conserto-paleteira-hidraulica-cascavel'
    | '/manutencao-paleteiras-hidraulicas-cascavel'
    | '/sobre-nos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsertoPaleteiraHidraulicaCascavelRoute: typeof ConsertoPaleteiraHidraulicaCascavelRoute
  ManutencaoPaleteirasHidraulicasCascavelRoute: typeof ManutencaoPaleteirasHidraulicasCascavelRoute
  SobreNosRoute: typeof SobreNosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-nos': {
      id: '/sobre-nos'
      path: '/sobre-nos'
      fullPath: '/sobre-nos'
      preLoaderRoute: typeof SobreNosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao-paleteiras-hidraulicas-cascavel': {
      id: '/manutencao-paleteiras-hidraulicas-cascavel'
      path: '/manutencao-paleteiras-hidraulicas-cascavel'
      fullPath: '/manutencao-paleteiras-hidraulicas-cascavel'
      preLoaderRoute: typeof ManutencaoPaleteirasHidraulicasCascavelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conserto-paleteira-hidraulica-cascavel': {
      id: '/conserto-paleteira-hidraulica-cascavel'
      path: '/conserto-paleteira-hidraulica-cascavel'
      fullPath: '/conserto-paleteira-hidraulica-cascavel'
      preLoaderRoute: typeof ConsertoPaleteiraHidraulicaCascavelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsertoPaleteiraHidraulicaCascavelRoute:
    ConsertoPaleteiraHidraulicaCascavelRoute,
  ManutencaoPaleteirasHidraulicasCascavelRoute:
    ManutencaoPaleteirasHidraulicasCascavelRoute,
  SobreNosRoute: SobreNosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
