/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendaPecasPaleteirasRouteImport } from './routes/venda-pecas-paleteiras'
import { Route as VendaPaleteirasHidraulicasCascavelRouteImport } from './routes/venda-paleteiras-hidraulicas-cascavel'
import { Route as SobreNosRouteImport } from './routes/sobre-nos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ManutencaoPaleteirasHidraulicasCascavelRouteImport } from './routes/manutencao-paleteiras-hidraulicas-cascavel'
import { Route as ManutencaoPaleteiraHidraulicaToledoRouteImport } from './routes/manutencao-paleteira-hidraulica-toledo'
import { Route as ManutencaoPaleteiraHidraulicaSantaHelenaRouteImport } from './routes/manutencao-paleteira-hidraulica-santa-helena'
import { Route as ManutencaoPaleteiraHidraulicaPalotinaRouteImport } from './routes/manutencao-paleteira-hidraulica-palotina'
import { Route as ManutencaoPaleteiraHidraulicaMedianeiraRouteImport } from './routes/manutencao-paleteira-hidraulica-medianeira'
import { Route as ManutencaoPaleteiraHidraulicaMarechalCandidoRondonRouteImport } from './routes/manutencao-paleteira-hidraulica-marechal-candido-rondon'
import { Route as ManutencaoPaleteiraHidraulicaFozDoIguacuRouteImport } from './routes/manutencao-paleteira-hidraulica-foz-do-iguacu'
import { Route as ManutencaoPaleteiraHidraulicaCorbeliaRouteImport } from './routes/manutencao-paleteira-hidraulica-corbelia'
import { Route as ManutencaoPaleteiraHidraulicaAssisChateaubriandRouteImport } from './routes/manutencao-paleteira-hidraulica-assis-chateaubriand'
import { Route as LocacaoPaleteirasHidraulicasCascavelRouteImport } from './routes/locacao-paleteiras-hidraulicas-cascavel'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConsertoPaleteiraHidraulicaCascavelRouteImport } from './routes/conserto-paleteira-hidraulica-cascavel'
import { Route as CidadesAtendidasRouteImport } from './routes/cidades-atendidas'
import { Route as AssistenciaTecnicaEquipamentosHidraulicosCascavelRouteImport } from './routes/assistencia-tecnica-equipamentos-hidraulicos-cascavel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogQuantoCustaConsertarPaleteiraHidraulicaRouteImport } from './routes/blog.quanto-custa-consertar-paleteira-hidraulica'
import { Route as BlogPrincipaisDefeitosPaleteiraHidraulicaRouteImport } from './routes/blog.principais-defeitos-paleteira-hidraulica'
import { Route as BlogPaleteiraManualVsHidraulicaRouteImport } from './routes/blog.paleteira-manual-vs-hidraulica'
import { Route as BlogManutencaoPreventivaPaleteiraHidraulicaRouteImport } from './routes/blog.manutencao-preventiva-paleteira-hidraulica'
import { Route as BlogLocacaoVsCompraPaleteiraCascavelRouteImport } from './routes/blog.locacao-vs-compra-paleteira-cascavel'
import { Route as BlogGuiaConsertoPaleteiraHidraulicaCascavelRouteImport } from './routes/blog.guia-conserto-paleteira-hidraulica-cascavel'
import { Route as BlogAluguelPaleteiraHidraulicaCascavelRouteImport } from './routes/blog.aluguel-paleteira-hidraulica-cascavel'

const VendaPecasPaleteirasRoute = VendaPecasPaleteirasRouteImport.update({
  id: '/venda-pecas-paleteiras',
  path: '/venda-pecas-paleteiras',
  getParentRoute: () => rootRouteImport,
} as any)
const VendaPaleteirasHidraulicasCascavelRoute =
  VendaPaleteirasHidraulicasCascavelRouteImport.update({
    id: '/venda-paleteiras-hidraulicas-cascavel',
    path: '/venda-paleteiras-hidraulicas-cascavel',
    getParentRoute: () => rootRouteImport,
  } as any)
const SobreNosRoute = SobreNosRouteImport.update({
  id: '/sobre-nos',
  path: '/sobre-nos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoPaleteirasHidraulicasCascavelRoute =
  ManutencaoPaleteirasHidraulicasCascavelRouteImport.update({
    id: '/manutencao-paleteiras-hidraulicas-cascavel',
    path: '/manutencao-paleteiras-hidraulicas-cascavel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManutencaoPaleteiraHidraulicaToledoRoute =
  ManutencaoPaleteiraHidraulicaToledoRouteImport.update({
    id: '/manutencao-paleteira-hidraulica-toledo',
    path: '/manutencao-paleteira-hidraulica-toledo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManutencaoPaleteiraHidraulicaSantaHelenaRoute =
  ManutencaoPaleteiraHidraulicaSantaHelenaRouteImport.update({
    id: '/manutencao-paleteira-hidraulica-santa-helena',
    path: '/manutencao-paleteira-hidraulica-santa-helena',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManutencaoPaleteiraHidraulicaPalotinaRoute =
  ManutencaoPaleteiraHidraulicaPalotinaRouteImport.update({
    id: '/manutencao-paleteira-hidraulica-palotina',
    path: '/manutencao-paleteira-hidraulica-palotina',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManutencaoPaleteiraHidraulicaMedianeiraRoute =
  ManutencaoPaleteiraHidraulicaMedianeiraRouteImport.update({
    id: '/manutencao-paleteira-hidraulica-medianeira',
    path: '/manutencao-paleteira-hidraulica-medianeira',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManutencaoPaleteiraHidraulicaMarechalCandidoRondonRoute =
  ManutencaoPaleteiraHidraulicaMarechalCandidoRondonRouteImport.update({
    id: '/manutencao-paleteira-hidraulica-marechal-candido-rondon',
    path: '/manutencao-paleteira-hidraulica-marechal-candido-rondon',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManutencaoPaleteiraHidraulicaFozDoIguacuRoute =
  ManutencaoPaleteiraHidraulicaFozDoIguacuRouteImport.update({
    id: '/manutencao-paleteira-hidraulica-foz-do-iguacu',
    path: '/manutencao-paleteira-hidraulica-foz-do-iguacu',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManutencaoPaleteiraHidraulicaCorbeliaRoute =
  ManutencaoPaleteiraHidraulicaCorbeliaRouteImport.update({
    id: '/manutencao-paleteira-hidraulica-corbelia',
    path: '/manutencao-paleteira-hidraulica-corbelia',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManutencaoPaleteiraHidraulicaAssisChateaubriandRoute =
  ManutencaoPaleteiraHidraulicaAssisChateaubriandRouteImport.update({
    id: '/manutencao-paleteira-hidraulica-assis-chateaubriand',
    path: '/manutencao-paleteira-hidraulica-assis-chateaubriand',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocacaoPaleteirasHidraulicasCascavelRoute =
  LocacaoPaleteirasHidraulicasCascavelRouteImport.update({
    id: '/locacao-paleteiras-hidraulicas-cascavel',
    path: '/locacao-paleteiras-hidraulicas-cascavel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsertoPaleteiraHidraulicaCascavelRoute =
  ConsertoPaleteiraHidraulicaCascavelRouteImport.update({
    id: '/conserto-paleteira-hidraulica-cascavel',
    path: '/conserto-paleteira-hidraulica-cascavel',
    getParentRoute: () => rootRouteImport,
  } as any)
const CidadesAtendidasRoute = CidadesAtendidasRouteImport.update({
  id: '/cidades-atendidas',
  path: '/cidades-atendidas',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenciaTecnicaEquipamentosHidraulicosCascavelRoute =
  AssistenciaTecnicaEquipamentosHidraulicosCascavelRouteImport.update({
    id: '/assistencia-tecnica-equipamentos-hidraulicos-cascavel',
    path: '/assistencia-tecnica-equipamentos-hidraulicos-cascavel',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogQuantoCustaConsertarPaleteiraHidraulicaRoute =
  BlogQuantoCustaConsertarPaleteiraHidraulicaRouteImport.update({
    id: '/blog/quanto-custa-consertar-paleteira-hidraulica',
    path: '/blog/quanto-custa-consertar-paleteira-hidraulica',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogPrincipaisDefeitosPaleteiraHidraulicaRoute =
  BlogPrincipaisDefeitosPaleteiraHidraulicaRouteImport.update({
    id: '/blog/principais-defeitos-paleteira-hidraulica',
    path: '/blog/principais-defeitos-paleteira-hidraulica',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogPaleteiraManualVsHidraulicaRoute =
  BlogPaleteiraManualVsHidraulicaRouteImport.update({
    id: '/blog/paleteira-manual-vs-hidraulica',
    path: '/blog/paleteira-manual-vs-hidraulica',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogManutencaoPreventivaPaleteiraHidraulicaRoute =
  BlogManutencaoPreventivaPaleteiraHidraulicaRouteImport.update({
    id: '/blog/manutencao-preventiva-paleteira-hidraulica',
    path: '/blog/manutencao-preventiva-paleteira-hidraulica',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogLocacaoVsCompraPaleteiraCascavelRoute =
  BlogLocacaoVsCompraPaleteiraCascavelRouteImport.update({
    id: '/blog/locacao-vs-compra-paleteira-cascavel',
    path: '/blog/locacao-vs-compra-paleteira-cascavel',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogGuiaConsertoPaleteiraHidraulicaCascavelRoute =
  BlogGuiaConsertoPaleteiraHidraulicaCascavelRouteImport.update({
    id: '/blog/guia-conserto-paleteira-hidraulica-cascavel',
    path: '/blog/guia-conserto-paleteira-hidraulica-cascavel',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogAluguelPaleteiraHidraulicaCascavelRoute =
  BlogAluguelPaleteiraHidraulicaCascavelRouteImport.update({
    id: '/blog/aluguel-paleteira-hidraulica-cascavel',
    path: '/blog/aluguel-paleteira-hidraulica-cascavel',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistencia-tecnica-equipamentos-hidraulicos-cascavel': typeof AssistenciaTecnicaEquipamentosHidraulicosCascavelRoute
  '/cidades-atendidas': typeof CidadesAtendidasRoute
  '/conserto-paleteira-hidraulica-cascavel': typeof ConsertoPaleteiraHidraulicaCascavelRoute
  '/contato': typeof ContatoRoute
  '/locacao-paleteiras-hidraulicas-cascavel': typeof LocacaoPaleteirasHidraulicasCascavelRoute
  '/manutencao-paleteira-hidraulica-assis-chateaubriand': typeof ManutencaoPaleteiraHidraulicaAssisChateaubriandRoute
  '/manutencao-paleteira-hidraulica-corbelia': typeof ManutencaoPaleteiraHidraulicaCorbeliaRoute
  '/manutencao-paleteira-hidraulica-foz-do-iguacu': typeof ManutencaoPaleteiraHidraulicaFozDoIguacuRoute
  '/manutencao-paleteira-hidraulica-marechal-candido-rondon': typeof ManutencaoPaleteiraHidraulicaMarechalCandidoRondonRoute
  '/manutencao-paleteira-hidraulica-medianeira': typeof ManutencaoPaleteiraHidraulicaMedianeiraRoute
  '/manutencao-paleteira-hidraulica-palotina': typeof ManutencaoPaleteiraHidraulicaPalotinaRoute
  '/manutencao-paleteira-hidraulica-santa-helena': typeof ManutencaoPaleteiraHidraulicaSantaHelenaRoute
  '/manutencao-paleteira-hidraulica-toledo': typeof ManutencaoPaleteiraHidraulicaToledoRoute
  '/manutencao-paleteiras-hidraulicas-cascavel': typeof ManutencaoPaleteirasHidraulicasCascavelRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nos': typeof SobreNosRoute
  '/venda-paleteiras-hidraulicas-cascavel': typeof VendaPaleteirasHidraulicasCascavelRoute
  '/venda-pecas-paleteiras': typeof VendaPecasPaleteirasRoute
  '/blog/aluguel-paleteira-hidraulica-cascavel': typeof BlogAluguelPaleteiraHidraulicaCascavelRoute
  '/blog/guia-conserto-paleteira-hidraulica-cascavel': typeof BlogGuiaConsertoPaleteiraHidraulicaCascavelRoute
  '/blog/locacao-vs-compra-paleteira-cascavel': typeof BlogLocacaoVsCompraPaleteiraCascavelRoute
  '/blog/manutencao-preventiva-paleteira-hidraulica': typeof BlogManutencaoPreventivaPaleteiraHidraulicaRoute
  '/blog/paleteira-manual-vs-hidraulica': typeof BlogPaleteiraManualVsHidraulicaRoute
  '/blog/principais-defeitos-paleteira-hidraulica': typeof BlogPrincipaisDefeitosPaleteiraHidraulicaRoute
  '/blog/quanto-custa-consertar-paleteira-hidraulica': typeof BlogQuantoCustaConsertarPaleteiraHidraulicaRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistencia-tecnica-equipamentos-hidraulicos-cascavel': typeof AssistenciaTecnicaEquipamentosHidraulicosCascavelRoute
  '/cidades-atendidas': typeof CidadesAtendidasRoute
  '/conserto-paleteira-hidraulica-cascavel': typeof ConsertoPaleteiraHidraulicaCascavelRoute
  '/contato': typeof ContatoRoute
  '/locacao-paleteiras-hidraulicas-cascavel': typeof LocacaoPaleteirasHidraulicasCascavelRoute
  '/manutencao-paleteira-hidraulica-assis-chateaubriand': typeof ManutencaoPaleteiraHidraulicaAssisChateaubriandRoute
  '/manutencao-paleteira-hidraulica-corbelia': typeof ManutencaoPaleteiraHidraulicaCorbeliaRoute
  '/manutencao-paleteira-hidraulica-foz-do-iguacu': typeof ManutencaoPaleteiraHidraulicaFozDoIguacuRoute
  '/manutencao-paleteira-hidraulica-marechal-candido-rondon': typeof ManutencaoPaleteiraHidraulicaMarechalCandidoRondonRoute
  '/manutencao-paleteira-hidraulica-medianeira': typeof ManutencaoPaleteiraHidraulicaMedianeiraRoute
  '/manutencao-paleteira-hidraulica-palotina': typeof ManutencaoPaleteiraHidraulicaPalotinaRoute
  '/manutencao-paleteira-hidraulica-santa-helena': typeof ManutencaoPaleteiraHidraulicaSantaHelenaRoute
  '/manutencao-paleteira-hidraulica-toledo': typeof ManutencaoPaleteiraHidraulicaToledoRoute
  '/manutencao-paleteiras-hidraulicas-cascavel': typeof ManutencaoPaleteirasHidraulicasCascavelRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nos': typeof SobreNosRoute
  '/venda-paleteiras-hidraulicas-cascavel': typeof VendaPaleteirasHidraulicasCascavelRoute
  '/venda-pecas-paleteiras': typeof VendaPecasPaleteirasRoute
  '/blog/aluguel-paleteira-hidraulica-cascavel': typeof BlogAluguelPaleteiraHidraulicaCascavelRoute
  '/blog/guia-conserto-paleteira-hidraulica-cascavel': typeof BlogGuiaConsertoPaleteiraHidraulicaCascavelRoute
  '/blog/locacao-vs-compra-paleteira-cascavel': typeof BlogLocacaoVsCompraPaleteiraCascavelRoute
  '/blog/manutencao-preventiva-paleteira-hidraulica': typeof BlogManutencaoPreventivaPaleteiraHidraulicaRoute
  '/blog/paleteira-manual-vs-hidraulica': typeof BlogPaleteiraManualVsHidraulicaRoute
  '/blog/principais-defeitos-paleteira-hidraulica': typeof BlogPrincipaisDefeitosPaleteiraHidraulicaRoute
  '/blog/quanto-custa-consertar-paleteira-hidraulica': typeof BlogQuantoCustaConsertarPaleteiraHidraulicaRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistencia-tecnica-equipamentos-hidraulicos-cascavel': typeof AssistenciaTecnicaEquipamentosHidraulicosCascavelRoute
  '/cidades-atendidas': typeof CidadesAtendidasRoute
  '/conserto-paleteira-hidraulica-cascavel': typeof ConsertoPaleteiraHidraulicaCascavelRoute
  '/contato': typeof ContatoRoute
  '/locacao-paleteiras-hidraulicas-cascavel': typeof LocacaoPaleteirasHidraulicasCascavelRoute
  '/manutencao-paleteira-hidraulica-assis-chateaubriand': typeof ManutencaoPaleteiraHidraulicaAssisChateaubriandRoute
  '/manutencao-paleteira-hidraulica-corbelia': typeof ManutencaoPaleteiraHidraulicaCorbeliaRoute
  '/manutencao-paleteira-hidraulica-foz-do-iguacu': typeof ManutencaoPaleteiraHidraulicaFozDoIguacuRoute
  '/manutencao-paleteira-hidraulica-marechal-candido-rondon': typeof ManutencaoPaleteiraHidraulicaMarechalCandidoRondonRoute
  '/manutencao-paleteira-hidraulica-medianeira': typeof ManutencaoPaleteiraHidraulicaMedianeiraRoute
  '/manutencao-paleteira-hidraulica-palotina': typeof ManutencaoPaleteiraHidraulicaPalotinaRoute
  '/manutencao-paleteira-hidraulica-santa-helena': typeof ManutencaoPaleteiraHidraulicaSantaHelenaRoute
  '/manutencao-paleteira-hidraulica-toledo': typeof ManutencaoPaleteiraHidraulicaToledoRoute
  '/manutencao-paleteiras-hidraulicas-cascavel': typeof ManutencaoPaleteirasHidraulicasCascavelRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nos': typeof SobreNosRoute
  '/venda-paleteiras-hidraulicas-cascavel': typeof VendaPaleteirasHidraulicasCascavelRoute
  '/venda-pecas-paleteiras': typeof VendaPecasPaleteirasRoute
  '/blog/aluguel-paleteira-hidraulica-cascavel': typeof BlogAluguelPaleteiraHidraulicaCascavelRoute
  '/blog/guia-conserto-paleteira-hidraulica-cascavel': typeof BlogGuiaConsertoPaleteiraHidraulicaCascavelRoute
  '/blog/locacao-vs-compra-paleteira-cascavel': typeof BlogLocacaoVsCompraPaleteiraCascavelRoute
  '/blog/manutencao-preventiva-paleteira-hidraulica': typeof BlogManutencaoPreventivaPaleteiraHidraulicaRoute
  '/blog/paleteira-manual-vs-hidraulica': typeof BlogPaleteiraManualVsHidraulicaRoute
  '/blog/principais-defeitos-paleteira-hidraulica': typeof BlogPrincipaisDefeitosPaleteiraHidraulicaRoute
  '/blog/quanto-custa-consertar-paleteira-hidraulica': typeof BlogQuantoCustaConsertarPaleteiraHidraulicaRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistencia-tecnica-equipamentos-hidraulicos-cascavel'
    | '/cidades-atendidas'
    | '/conserto-paleteira-hidraulica-cascavel'
    | '/contato'
    | '/locacao-paleteiras-hidraulicas-cascavel'
    | '/manutencao-paleteira-hidraulica-assis-chateaubriand'
    | '/manutencao-paleteira-hidraulica-corbelia'
    | '/manutencao-paleteira-hidraulica-foz-do-iguacu'
    | '/manutencao-paleteira-hidraulica-marechal-candido-rondon'
    | '/manutencao-paleteira-hidraulica-medianeira'
    | '/manutencao-paleteira-hidraulica-palotina'
    | '/manutencao-paleteira-hidraulica-santa-helena'
    | '/manutencao-paleteira-hidraulica-toledo'
    | '/manutencao-paleteiras-hidraulicas-cascavel'
    | '/sitemap.xml'
    | '/sobre-nos'
    | '/venda-paleteiras-hidraulicas-cascavel'
    | '/venda-pecas-paleteiras'
    | '/blog/aluguel-paleteira-hidraulica-cascavel'
    | '/blog/guia-conserto-paleteira-hidraulica-cascavel'
    | '/blog/locacao-vs-compra-paleteira-cascavel'
    | '/blog/manutencao-preventiva-paleteira-hidraulica'
    | '/blog/paleteira-manual-vs-hidraulica'
    | '/blog/principais-defeitos-paleteira-hidraulica'
    | '/blog/quanto-custa-consertar-paleteira-hidraulica'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistencia-tecnica-equipamentos-hidraulicos-cascavel'
    | '/cidades-atendidas'
    | '/conserto-paleteira-hidraulica-cascavel'
    | '/contato'
    | '/locacao-paleteiras-hidraulicas-cascavel'
    | '/manutencao-paleteira-hidraulica-assis-chateaubriand'
    | '/manutencao-paleteira-hidraulica-corbelia'
    | '/manutencao-paleteira-hidraulica-foz-do-iguacu'
    | '/manutencao-paleteira-hidraulica-marechal-candido-rondon'
    | '/manutencao-paleteira-hidraulica-medianeira'
    | '/manutencao-paleteira-hidraulica-palotina'
    | '/manutencao-paleteira-hidraulica-santa-helena'
    | '/manutencao-paleteira-hidraulica-toledo'
    | '/manutencao-paleteiras-hidraulicas-cascavel'
    | '/sitemap.xml'
    | '/sobre-nos'
    | '/venda-paleteiras-hidraulicas-cascavel'
    | '/venda-pecas-paleteiras'
    | '/blog/aluguel-paleteira-hidraulica-cascavel'
    | '/blog/guia-conserto-paleteira-hidraulica-cascavel'
    | '/blog/locacao-vs-compra-paleteira-cascavel'
    | '/blog/manutencao-preventiva-paleteira-hidraulica'
    | '/blog/paleteira-manual-vs-hidraulica'
    | '/blog/principais-defeitos-paleteira-hidraulica'
    | '/blog/quanto-custa-consertar-paleteira-hidraulica'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/assistencia-tecnica-equipamentos-hidraulicos-cascavel'
    | '/cidades-atendidas'
    | '/conserto-paleteira-hidraulica-cascavel'
    | '/contato'
    | '/locacao-paleteiras-hidraulicas-cascavel'
    | '/manutencao-paleteira-hidraulica-assis-chateaubriand'
    | '/manutencao-paleteira-hidraulica-corbelia'
    | '/manutencao-paleteira-hidraulica-foz-do-iguacu'
    | '/manutencao-paleteira-hidraulica-marechal-candido-rondon'
    | '/manutencao-paleteira-hidraulica-medianeira'
    | '/manutencao-paleteira-hidraulica-palotina'
    | '/manutencao-paleteira-hidraulica-santa-helena'
    | '/manutencao-paleteira-hidraulica-toledo'
    | '/manutencao-paleteiras-hidraulicas-cascavel'
    | '/sitemap.xml'
    | '/sobre-nos'
    | '/venda-paleteiras-hidraulicas-cascavel'
    | '/venda-pecas-paleteiras'
    | '/blog/aluguel-paleteira-hidraulica-cascavel'
    | '/blog/guia-conserto-paleteira-hidraulica-cascavel'
    | '/blog/locacao-vs-compra-paleteira-cascavel'
    | '/blog/manutencao-preventiva-paleteira-hidraulica'
    | '/blog/paleteira-manual-vs-hidraulica'
    | '/blog/principais-defeitos-paleteira-hidraulica'
    | '/blog/quanto-custa-consertar-paleteira-hidraulica'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistenciaTecnicaEquipamentosHidraulicosCascavelRoute: typeof AssistenciaTecnicaEquipamentosHidraulicosCascavelRoute
  CidadesAtendidasRoute: typeof CidadesAtendidasRoute
  ConsertoPaleteiraHidraulicaCascavelRoute: typeof ConsertoPaleteiraHidraulicaCascavelRoute
  ContatoRoute: typeof ContatoRoute
  LocacaoPaleteirasHidraulicasCascavelRoute: typeof LocacaoPaleteirasHidraulicasCascavelRoute
  ManutencaoPaleteiraHidraulicaAssisChateaubriandRoute: typeof ManutencaoPaleteiraHidraulicaAssisChateaubriandRoute
  ManutencaoPaleteiraHidraulicaCorbeliaRoute: typeof ManutencaoPaleteiraHidraulicaCorbeliaRoute
  ManutencaoPaleteiraHidraulicaFozDoIguacuRoute: typeof ManutencaoPaleteiraHidraulicaFozDoIguacuRoute
  ManutencaoPaleteiraHidraulicaMarechalCandidoRondonRoute: typeof ManutencaoPaleteiraHidraulicaMarechalCandidoRondonRoute
  ManutencaoPaleteiraHidraulicaMedianeiraRoute: typeof ManutencaoPaleteiraHidraulicaMedianeiraRoute
  ManutencaoPaleteiraHidraulicaPalotinaRoute: typeof ManutencaoPaleteiraHidraulicaPalotinaRoute
  ManutencaoPaleteiraHidraulicaSantaHelenaRoute: typeof ManutencaoPaleteiraHidraulicaSantaHelenaRoute
  ManutencaoPaleteiraHidraulicaToledoRoute: typeof ManutencaoPaleteiraHidraulicaToledoRoute
  ManutencaoPaleteirasHidraulicasCascavelRoute: typeof ManutencaoPaleteirasHidraulicasCascavelRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreNosRoute: typeof SobreNosRoute
  VendaPaleteirasHidraulicasCascavelRoute: typeof VendaPaleteirasHidraulicasCascavelRoute
  VendaPecasPaleteirasRoute: typeof VendaPecasPaleteirasRoute
  BlogAluguelPaleteiraHidraulicaCascavelRoute: typeof BlogAluguelPaleteiraHidraulicaCascavelRoute
  BlogGuiaConsertoPaleteiraHidraulicaCascavelRoute: typeof BlogGuiaConsertoPaleteiraHidraulicaCascavelRoute
  BlogLocacaoVsCompraPaleteiraCascavelRoute: typeof BlogLocacaoVsCompraPaleteiraCascavelRoute
  BlogManutencaoPreventivaPaleteiraHidraulicaRoute: typeof BlogManutencaoPreventivaPaleteiraHidraulicaRoute
  BlogPaleteiraManualVsHidraulicaRoute: typeof BlogPaleteiraManualVsHidraulicaRoute
  BlogPrincipaisDefeitosPaleteiraHidraulicaRoute: typeof BlogPrincipaisDefeitosPaleteiraHidraulicaRoute
  BlogQuantoCustaConsertarPaleteiraHidraulicaRoute: typeof BlogQuantoCustaConsertarPaleteiraHidraulicaRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venda-pecas-paleteiras': {
      id: '/venda-pecas-paleteiras'
      path: '/venda-pecas-paleteiras'
      fullPath: '/venda-pecas-paleteiras'
      preLoaderRoute: typeof VendaPecasPaleteirasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venda-paleteiras-hidraulicas-cascavel': {
      id: '/venda-paleteiras-hidraulicas-cascavel'
      path: '/venda-paleteiras-hidraulicas-cascavel'
      fullPath: '/venda-paleteiras-hidraulicas-cascavel'
      preLoaderRoute: typeof VendaPaleteirasHidraulicasCascavelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nos': {
      id: '/sobre-nos'
      path: '/sobre-nos'
      fullPath: '/sobre-nos'
      preLoaderRoute: typeof SobreNosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao-paleteiras-hidraulicas-cascavel': {
      id: '/manutencao-paleteiras-hidraulicas-cascavel'
      path: '/manutencao-paleteiras-hidraulicas-cascavel'
      fullPath: '/manutencao-paleteiras-hidraulicas-cascavel'
      preLoaderRoute: typeof ManutencaoPaleteirasHidraulicasCascavelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao-paleteira-hidraulica-toledo': {
      id: '/manutencao-paleteira-hidraulica-toledo'
      path: '/manutencao-paleteira-hidraulica-toledo'
      fullPath: '/manutencao-paleteira-hidraulica-toledo'
      preLoaderRoute: typeof ManutencaoPaleteiraHidraulicaToledoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao-paleteira-hidraulica-santa-helena': {
      id: '/manutencao-paleteira-hidraulica-santa-helena'
      path: '/manutencao-paleteira-hidraulica-santa-helena'
      fullPath: '/manutencao-paleteira-hidraulica-santa-helena'
      preLoaderRoute: typeof ManutencaoPaleteiraHidraulicaSantaHelenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao-paleteira-hidraulica-palotina': {
      id: '/manutencao-paleteira-hidraulica-palotina'
      path: '/manutencao-paleteira-hidraulica-palotina'
      fullPath: '/manutencao-paleteira-hidraulica-palotina'
      preLoaderRoute: typeof ManutencaoPaleteiraHidraulicaPalotinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao-paleteira-hidraulica-medianeira': {
      id: '/manutencao-paleteira-hidraulica-medianeira'
      path: '/manutencao-paleteira-hidraulica-medianeira'
      fullPath: '/manutencao-paleteira-hidraulica-medianeira'
      preLoaderRoute: typeof ManutencaoPaleteiraHidraulicaMedianeiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao-paleteira-hidraulica-marechal-candido-rondon': {
      id: '/manutencao-paleteira-hidraulica-marechal-candido-rondon'
      path: '/manutencao-paleteira-hidraulica-marechal-candido-rondon'
      fullPath: '/manutencao-paleteira-hidraulica-marechal-candido-rondon'
      preLoaderRoute: typeof ManutencaoPaleteiraHidraulicaMarechalCandidoRondonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao-paleteira-hidraulica-foz-do-iguacu': {
      id: '/manutencao-paleteira-hidraulica-foz-do-iguacu'
      path: '/manutencao-paleteira-hidraulica-foz-do-iguacu'
      fullPath: '/manutencao-paleteira-hidraulica-foz-do-iguacu'
      preLoaderRoute: typeof ManutencaoPaleteiraHidraulicaFozDoIguacuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao-paleteira-hidraulica-corbelia': {
      id: '/manutencao-paleteira-hidraulica-corbelia'
      path: '/manutencao-paleteira-hidraulica-corbelia'
      fullPath: '/manutencao-paleteira-hidraulica-corbelia'
      preLoaderRoute: typeof ManutencaoPaleteiraHidraulicaCorbeliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao-paleteira-hidraulica-assis-chateaubriand': {
      id: '/manutencao-paleteira-hidraulica-assis-chateaubriand'
      path: '/manutencao-paleteira-hidraulica-assis-chateaubriand'
      fullPath: '/manutencao-paleteira-hidraulica-assis-chateaubriand'
      preLoaderRoute: typeof ManutencaoPaleteiraHidraulicaAssisChateaubriandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locacao-paleteiras-hidraulicas-cascavel': {
      id: '/locacao-paleteiras-hidraulicas-cascavel'
      path: '/locacao-paleteiras-hidraulicas-cascavel'
      fullPath: '/locacao-paleteiras-hidraulicas-cascavel'
      preLoaderRoute: typeof LocacaoPaleteirasHidraulicasCascavelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conserto-paleteira-hidraulica-cascavel': {
      id: '/conserto-paleteira-hidraulica-cascavel'
      path: '/conserto-paleteira-hidraulica-cascavel'
      fullPath: '/conserto-paleteira-hidraulica-cascavel'
      preLoaderRoute: typeof ConsertoPaleteiraHidraulicaCascavelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cidades-atendidas': {
      id: '/cidades-atendidas'
      path: '/cidades-atendidas'
      fullPath: '/cidades-atendidas'
      preLoaderRoute: typeof CidadesAtendidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistencia-tecnica-equipamentos-hidraulicos-cascavel': {
      id: '/assistencia-tecnica-equipamentos-hidraulicos-cascavel'
      path: '/assistencia-tecnica-equipamentos-hidraulicos-cascavel'
      fullPath: '/assistencia-tecnica-equipamentos-hidraulicos-cascavel'
      preLoaderRoute: typeof AssistenciaTecnicaEquipamentosHidraulicosCascavelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/quanto-custa-consertar-paleteira-hidraulica': {
      id: '/blog/quanto-custa-consertar-paleteira-hidraulica'
      path: '/blog/quanto-custa-consertar-paleteira-hidraulica'
      fullPath: '/blog/quanto-custa-consertar-paleteira-hidraulica'
      preLoaderRoute: typeof BlogQuantoCustaConsertarPaleteiraHidraulicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/principais-defeitos-paleteira-hidraulica': {
      id: '/blog/principais-defeitos-paleteira-hidraulica'
      path: '/blog/principais-defeitos-paleteira-hidraulica'
      fullPath: '/blog/principais-defeitos-paleteira-hidraulica'
      preLoaderRoute: typeof BlogPrincipaisDefeitosPaleteiraHidraulicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/paleteira-manual-vs-hidraulica': {
      id: '/blog/paleteira-manual-vs-hidraulica'
      path: '/blog/paleteira-manual-vs-hidraulica'
      fullPath: '/blog/paleteira-manual-vs-hidraulica'
      preLoaderRoute: typeof BlogPaleteiraManualVsHidraulicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/manutencao-preventiva-paleteira-hidraulica': {
      id: '/blog/manutencao-preventiva-paleteira-hidraulica'
      path: '/blog/manutencao-preventiva-paleteira-hidraulica'
      fullPath: '/blog/manutencao-preventiva-paleteira-hidraulica'
      preLoaderRoute: typeof BlogManutencaoPreventivaPaleteiraHidraulicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/locacao-vs-compra-paleteira-cascavel': {
      id: '/blog/locacao-vs-compra-paleteira-cascavel'
      path: '/blog/locacao-vs-compra-paleteira-cascavel'
      fullPath: '/blog/locacao-vs-compra-paleteira-cascavel'
      preLoaderRoute: typeof BlogLocacaoVsCompraPaleteiraCascavelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/guia-conserto-paleteira-hidraulica-cascavel': {
      id: '/blog/guia-conserto-paleteira-hidraulica-cascavel'
      path: '/blog/guia-conserto-paleteira-hidraulica-cascavel'
      fullPath: '/blog/guia-conserto-paleteira-hidraulica-cascavel'
      preLoaderRoute: typeof BlogGuiaConsertoPaleteiraHidraulicaCascavelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/aluguel-paleteira-hidraulica-cascavel': {
      id: '/blog/aluguel-paleteira-hidraulica-cascavel'
      path: '/blog/aluguel-paleteira-hidraulica-cascavel'
      fullPath: '/blog/aluguel-paleteira-hidraulica-cascavel'
      preLoaderRoute: typeof BlogAluguelPaleteiraHidraulicaCascavelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistenciaTecnicaEquipamentosHidraulicosCascavelRoute:
    AssistenciaTecnicaEquipamentosHidraulicosCascavelRoute,
  CidadesAtendidasRoute: CidadesAtendidasRoute,
  ConsertoPaleteiraHidraulicaCascavelRoute:
    ConsertoPaleteiraHidraulicaCascavelRoute,
  ContatoRoute: ContatoRoute,
  LocacaoPaleteirasHidraulicasCascavelRoute:
    LocacaoPaleteirasHidraulicasCascavelRoute,
  ManutencaoPaleteiraHidraulicaAssisChateaubriandRoute:
    ManutencaoPaleteiraHidraulicaAssisChateaubriandRoute,
  ManutencaoPaleteiraHidraulicaCorbeliaRoute:
    ManutencaoPaleteiraHidraulicaCorbeliaRoute,
  ManutencaoPaleteiraHidraulicaFozDoIguacuRoute:
    ManutencaoPaleteiraHidraulicaFozDoIguacuRoute,
  ManutencaoPaleteiraHidraulicaMarechalCandidoRondonRoute:
    ManutencaoPaleteiraHidraulicaMarechalCandidoRondonRoute,
  ManutencaoPaleteiraHidraulicaMedianeiraRoute:
    ManutencaoPaleteiraHidraulicaMedianeiraRoute,
  ManutencaoPaleteiraHidraulicaPalotinaRoute:
    ManutencaoPaleteiraHidraulicaPalotinaRoute,
  ManutencaoPaleteiraHidraulicaSantaHelenaRoute:
    ManutencaoPaleteiraHidraulicaSantaHelenaRoute,
  ManutencaoPaleteiraHidraulicaToledoRoute:
    ManutencaoPaleteiraHidraulicaToledoRoute,
  ManutencaoPaleteirasHidraulicasCascavelRoute:
    ManutencaoPaleteirasHidraulicasCascavelRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreNosRoute: SobreNosRoute,
  VendaPaleteirasHidraulicasCascavelRoute:
    VendaPaleteirasHidraulicasCascavelRoute,
  VendaPecasPaleteirasRoute: VendaPecasPaleteirasRoute,
  BlogAluguelPaleteiraHidraulicaCascavelRoute:
    BlogAluguelPaleteiraHidraulicaCascavelRoute,
  BlogGuiaConsertoPaleteiraHidraulicaCascavelRoute:
    BlogGuiaConsertoPaleteiraHidraulicaCascavelRoute,
  BlogLocacaoVsCompraPaleteiraCascavelRoute:
    BlogLocacaoVsCompraPaleteiraCascavelRoute,
  BlogManutencaoPreventivaPaleteiraHidraulicaRoute:
    BlogManutencaoPreventivaPaleteiraHidraulicaRoute,
  BlogPaleteiraManualVsHidraulicaRoute: BlogPaleteiraManualVsHidraulicaRoute,
  BlogPrincipaisDefeitosPaleteiraHidraulicaRoute:
    BlogPrincipaisDefeitosPaleteiraHidraulicaRoute,
  BlogQuantoCustaConsertarPaleteiraHidraulicaRoute:
    BlogQuantoCustaConsertarPaleteiraHidraulicaRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
